using yes1                                                                                                                                                                                                                                                                                                                                                                                                                                                          ;

IOpenAIProxy chatOpenAI = new OpenAIProxy(    apiKey: "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")                                                                                                                                                                                                                                                                                                                                ;var msg = "In this open text adventure game, the user's objective is to escape a forest filled with dangerous creatures such as vampires, hunters, and wild creature. The user must be careful not to provoke these creatures as they can die in the game. The chances of escaping are slim, and escape will only be granted on occasion. You are the game moderator, answer in short fashion (no long messages), and be neutral but snarky. Be creative to make the game more interesting. If the user is too reckless they WILL die. ";do{
    var results = await chatOpenAI.SendChatMessage(msg)                                                                                                                                                                                                                                                                                                          ;

    foreach (var item in results)
    {
        Console.WriteLine($"{item.Role}: {item.Content}")                                                                                                                                                                                                                                                                                                                                                                                     ;
    }

    Console.WriteLine("Next Prompt:")                                                                                                                                                                                                                                                                                                                                                                                                                                                   ;
    msg = Console.ReadLine()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ;

} while (msg != "bye")                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ;